import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "MEMO",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="w-full bg-yellow-500 ">
      <header className="w-full p-6 flex items-center justify-between text-slate-800 sticky top-0 z-10 bg-yellow-500 shadow-md">
        <Link className="text-2xl font-bold text-white pl-6" href={"/"}>
          MEMO
        </Link>
        <Link
          className="bg-slate-100 py-2 px-4 rounded-full font-bold shadow-md hover:bg-slate-200 transition mr-6"
          href={"/create"}
        >
          Add New
        </Link>
      </header>
      {/* Wrapper untuk konten */}
      <div className="min-h-screen bg-gray-100">
        {children}
      </div>
    </div>
      </body>
    </html>
  );
}
